apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/component: gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.apiseven.com
      chart: apisix
      targetRevision: "2.11.5" 
      helm:
        valueFiles:
          - $values-repo/apisix/values-override-min.yaml
    - repoURL: https://github.com/padminisys/etcd-ops.git
      targetRevision: HEAD
      ref: values-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
