# app-etcd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/padminisys/etcd-ops.git
    targetRevision: main
    path: manifests/etcd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix   # default target; your manifests also pin namespace explicitly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
