# manifests/etcd/app-etcd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/REPLACE_ME/etcd-statefulset.git
    targetRevision: main
    path: manifests/etcd
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
