# manifests/etcd/cert-etcd-internal.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-internal
  namespace: apisix
spec:
  secretName: etcd-internal-tls
  issuerRef:
    name: etcd-ca
    kind: Issuer
  commonName: etcd
  usages: ["digital signature","key encipherment","server auth","client auth"]
  renewBefore: 720h     # 30d before expiry
  duration: 8760h       # 1y
  dnsNames:
    - etcd
    - etcd.apisix
    - etcd.apisix.svc
    - etcd.apisix.svc.cluster.local
    - etcd-0
    - etcd-0.etcd
    - etcd-0.etcd.apisix
    - etcd-0.etcd.apisix.svc
    - etcd-0.etcd.apisix.svc.cluster.local
    - etcd-1
    - etcd-1.etcd
    - etcd-1.etcd.apisix
    - etcd-1.etcd.apisix.svc
    - etcd-1.etcd.apisix.svc.cluster.local
    - etcd-2
    - etcd-2.etcd
    - etcd-2.etcd.apisix
    - etcd-2.etcd.apisix.svc
    - etcd-2.etcd.apisix.svc.cluster.local
    - etcd.padmini.systems