apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etcd-public
  namespace: apisix
  labels:
    app: etcd
    component: database
    version: v3.6.0
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # gRPC over **TLS** to backend (this was the missing piece)
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    # 🔒 Optional: restrict who can hit the edge (fill in your real IPs)
    # nginx.ingress.kubernetes.io/whitelist-source-range: "203.0.113.10/32,198.51.100.22/32"

    # TLS to etcd backend: verify etcd's cert with your CA; no client cert presented
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "2"
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "etcd.apisix.svc.cluster.local"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "apisix/etcd-nginx-client" # must contain ca.crt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - etcd.padmini.systems
    secretName: etcd-padmini-tls
  rules:
  - host: etcd.padmini.systems
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: etcd-client
            port:
              number: 2379
