# manifests/etcd/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: etcd-ingress
  namespace: apisix
  labels:
    app: etcd
    component: database
    version: v3.6.0
spec:
  podSelector:
    matchLabels:
      app: etcd
  policyTypes:
  - Ingress
  ingress:
  # 1) Allow client 2379 + metrics 8080 from pods in the apisix namespace (debug/tools/APISIX)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: apisix
      podSelector: {}
    ports:
    - port: 2379
      protocol: TCP
    - port: 8080
      protocol: TCP

  # 2) Allow client 2379 from ingress-nginx (pod IP path) and from node IPs (hostNetwork path)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector: {}
    - ipBlock:
        cidr: 89.58.47.216/32     # ← your node public IP (update if different)
    - ipBlock:
        cidr: 185.228.136.185/32  # ← your other node public IP
    ports:
    - port: 2379
      protocol: TCP

  # 3) Allow 2380 (peer) only between etcd pods in the same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: apisix
      podSelector:
        matchLabels:
          app: etcd
    ports:
    - port: 2380
      protocol: TCP
