# manifests/etcd/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: etcd-pdb
  namespace: apisix
  labels:
    app: etcd
    component: database
    version: v3.6.0
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: etcd
