# .github/workflows/apply-argocd.yml
name: Apply Argo CD Application

on:
  push:
    branches: [ main ]
    paths:
      - 'app-*.yaml'                 # ← include both apps
      - 'manifests/**'
      - 'apisix/**'                  # ← pick up values file changes
      - '.github/workflows/apply-argocd.yml'
  workflow_dispatch:

env:
  KUBECTL_VERSION: 'v1.33.2'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.PSYS_CENTOS_1_KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl cluster-info

      - name: Verify Argo CD CRD
        run: |
          kubectl get ns argocd
          kubectl get crd applications.argoproj.io

      - name: Apply Applications (etcd first, then apisix)
        run: |
          # Order of apply doesn't strictly matter—sync-wave controls real order—
          # but we'll apply etcd first for clarity.
          kubectl apply -f app-etcd.yaml
          kubectl apply -f app-apisix.yaml
          echo "--- Current Application statuses ---"
          kubectl -n argocd get applications
